### ISSUE TITLE
Appending fields through JS assigns the wrong ID

### ISSUE THREAD

**Issue by tombroomfield** [danielpclark/dynaspan#1]
Hi,
When dynamically adding dynaspan_text_fields to a page, the id of the field conflicts with existing fields, causing the wrong field to become editable when you click on the dynamically created field.

**Comment by danielpclark** [comment]
Are you dynamically adding it via JavaScript?  The Ruby method increments the ID once per template rendering.

**Comment by tombroomfield** [comment]
Yes, through a rendered js file from a controller action:

``` js
$('.section-sort').append('<%= escape_javascript(render "admin/templates/section_row", section: @section) %>')
```

**Comment by tombroomfield** [comment]
I have somewhat solved it by prepending a random string to the dynaspan_counter, not a great solution though.

**Comment by danielpclark** [comment]
If the ruby code runs each time the counter should work.  Make sure the resource isn't being cached as just one copy.

**Comment by tombroomfield** [comment]
I think the issue is that there are already dyna_text elements on the page, with an ids of '1', '2'... ect. Once I generate a new one dynamically, it sets it back to 1, and you get a conflict.

**Comment by danielpclark** [comment]
Oh I get it.  The helper is being used in a different context rather than being built into one view.  I find that odd...  Can you add the word `partial:` to your render command.  That should fix the numbering (it should keep the variable built within the same scope).

**Comment by danielpclark** [comment]
I have partials numbering fine in my own system.

**Comment by danielpclark** [comment]
Although I don't have my partials injected with JavaScript... They are simply inline in the erb template.

**Comment by tombroomfield** [comment]
Yeah, it works fine as long as I have them all inline, I render them through JS when I create a new record, it then gets dynamically added to the page, does that make sense?

**Comment by danielpclark** [comment]
Yeah.  I'll have a beta release up in a few minutes.  It'll have an manual ID input option as well as custom form methods.  I'm doing a beta because I don't have a test suite at the moment.  The new features should be tested and I need to verify that nothing is broken.

**Comment by tombroomfield** [comment]
Yeah awesome sounds good, let me know when you want me to give it a try.

**Comment by danielpclark** [comment]
Alright try out the latest beta.

``` ruby
# Gemfile
gem 'dynaspan', '0.1.2.beta1'
```

The dynaspan commands now accept two additional fields in the options Hash (which is the last parameter you give).

The options are:

``` ruby
{
  unique_id: 12346215325612,
  form_for: {
    url: my_namespaced_path_here
  }
}
```

The **form_for** parameter can take any **form_for** Hash option available in Ruby. http://apidock.com/rails/ActionView/Helpers/FormHelper/form_for

I'd appreciate if you tried it out and let me know if you find any bugs.

**Comment by danielpclark** [comment]
You can try a separate unique numbering system for JavaScript renders.  prepend js on it or something.

**Comment by danielpclark** [comment]
Nothing is broken on my site with the update so that's good news.

**Comment by tombroomfield** [comment]
I am getting undefined method `section_path' for #<#Class:0x007fe87cef0c88:0x007fe88222e850> on the beta. Any ideas?

**Comment by danielpclark** [comment]
I believe that's the helper you're handing the form_for.  Try an alternative way of pointing to the resource.

**Comment by danielpclark** [comment]
``` ruby
{
  unique_id: 12346215325612,
  form_for: {
    url: section_path
  }
}
```

maybe `url: "admin/#{section_path}"` ???

Does your helper include the admin path?

**Comment by tombroomfield** [comment]
Ah, I see, that is perfect I think.

**Comment by tombroomfield** [comment]
Works absolutely perfectly, thanks for that. Will be using this a lot throughout the current project.

**Comment by danielpclark** [comment]
Excellent ^_^

**Comment by tombroomfield** [comment]
Add a side note, I am just using the actual model id as the unique id, really nice solution to avoid conflicts.

**Comment by danielpclark** [comment]
As long as you don't have two different objects types conflict that will work.  It might be a good idea to do `[@thing.class.name, @thing.id].join` so the different objects wont conflict.

**Comment by tombroomfield** [comment]
Yep, it will also conflict with different fields within the same object, so I am doing this: "class_name-field_name-object_id", works great.

**Comment by danielpclark** [comment]
Hey Tom,  I just want to make sure.  You've tested both the **form_for** parameters and the **unique_id** parameter?  I'm planning on writing up the readme and finalizing the version.

**Comment by tombroomfield** [comment]
Hi Daniel, yes, it is working great for me. I wonder if the current implementation will confuse some people around the form_for attribute. Generally with the rails form, you just pass in an object, or an object with an array for namespace: [:admin, @user]. That being said, if you get it covered in the docs it should work fine. Functionality is working perfectly for me though, ability to use it after they have been dynamically created makes it super flexible,
thanks for your work on this :+1:

**Comment by danielpclark** [comment]
https://github.com/danielpclark/dynaspan/tree/v0.1.2
